services:
  web:
    image: nginx
    # 配置此项便会随docker启动而启动
    restart: always
    volumes:
    - ./docs/.vuepress/dist:/usr/share/nginx/html
    ports:
    - "10010:80"
    environment:
    - NGINX_HOST=foobar.com
    - NGINX_PORT=80
